Initialize AdmissibilityCondition::ratio_
g++ 13.1.0 may report a warning when deriving new admissibility conditions
from AdmissibilityCondition:

    In copy constructor ‘constexpr hmat::AdmissibilityCondition::AdmissibilityCondition(const hmat::AdmissibilityCondition&)’,
    hmat-oss/src/admissibility.hpp:39:7: error: ‘AdmissibilityCondition::ratio_’ may be used uninitialized [-Werror=maybe-uninitialized]

In StandardAdmissibilityCondition constructor we use 0 as default value,
so it seems reasonable to use the same default in AdmissibilityCondition.